CC = gcc

all:
	@ $(CC) -o worker1 worker_1.cpp 
	@ $(CC) -o worker2 worker_2.cpp 
	@ $(CC) -o worker3 worker_3.cpp 
	@ $(CC) -o main main.c

main:
	@ $(CC) -o main main.c

workers:
	@ $(CC) -o worker1 worker_1.cpp 
	@ $(CC) -o worker2 worker_2.cpp 
	@ $(CC) -o worker3 worker_3.cpp 